ARG SERVER_PORT=3001

FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap && yarn build:server

EXPOSE $SERVER_PORT

CMD [ "yarn", "run", "start:server" ]
