ARG CLIENT_PORT=3000

FROM node:18

WORKDIR /app

COPY package.json ./

RUN yarn install

COPY . .

RUN yarn lerna bootstrap && yarn build:client

EXPOSE $CLIENT_PORT

CMD [ "yarn", "run", "start:client" ]
