ARG SERVER_PORT=3001

FROM node:18

WORKDIR /app

COPY package.json ./

RUN yarn install

COPY . .

RUN yarn lerna bootstrap && yarn build:server

EXPOSE $SERVER_PORT

CMD [ "yarn", "run", "start:server" ]
