ARG CLIENT_PORT=3000

FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap && yarn build:client

EXPOSE $CLIENT_PORT

CMD [ "yarn", "run", "start:client" ]
