// TODO: Добавить выбор и покупку пакетов смайлов в настройках игрока
/** Типы доступных пакетов смайлов */
export enum EmojiPack {
  /** Пак с эмоциями в виде киберкубика */
  Dice="dice",
}

/** Типы доступных смайликов */
export enum Emoji {
  Frowning='☹',
  Smiling='☺',
  ThumbsUp='👍',
  ThumbsDown='👎',
  AngryWithHorns='👿',
  BlueHeart='💙',
  PurpleHeart='💜',
  BlackHeart='🖤',
  Hugging='🤗',
  RollingOnTheFloorLaughing='🤣',
  WithHandOverMouth='🤭',
  SmilingHearts='🥰',
  Hot='🥵',
  Grinning='😀',
  BeamingSmilingEyes='😁',
  TearsOfJoy='😂',
  GrinningBigEyes='😄',
  GrinningSweat='😅',
  SmilingHalo='😇',
  SmilingHorns='😈',
  Winking='😉',
  SavoringFood='😋',
  SmilingHeartEyes='😍',
  SmilingSunglasses='😎',
  Neutral='😐',
  Expressionless='😑',
  Downcast='😓',
  Confused='😕',
  Confounded='😖',
  Kissing='😗',
  BlowingKiss='😘',
  KissingSmilingEyes='😙',
  Tongue='😛',
  WinkingTongue='😜',
  Disappointed='😞',
  Angry='😠',
  Persevering='😣',
  SadButRelieved='😥',
  Fearful='😨',
  Sleepy='😪',
  Tired='😫',
  LoudlyCrying='😭',
  AnxiousSweat='😰',
  ScreamingInFear='😱',
  Astonished='😲',
  Flushed='😳',
  Sleeping='😴',
  WithoutMouth='😶',
  MedicalMask='😷',
  SlightlyFrowning='🙁',
  SlightlySmiling='🙂',
}
